---
language: python

python:
  - '3.8'

install:
    - make dev_env

env:
    PYTHONPATH=$(pwd)

script:
    - make tests

deploy:
  provider: heroku
  api_key:
    secure: "eAay3X1KsXU7wOQQhhYZJlRxcDZ3qNhBFJB3K59eYc7FQTGm2RK6pHLqCzl7csEUNRkZ/nCxpQRis4y0sSNtjPzXRU7jxB/WasnHfjvwHjVCVpv8FGPAOdV3ziFx6lHoQNFY0SghUfSo+THjrBAKifdW58j3mrNHuSFI3FJw+QNkEma1ZtxzLDuqvT3WbTfzB2bmEQGMVrmrdZLchytGlhlBEr0zxbZbuUDB+HhyJBiR03wynlcID4Ajb859FWUQj6SRRqGP6PWwJvqOS4P26fnxXn82SqbhtcMAZHjknFEV+beuIQ5kOxcvNU3q0pSSvrWlGAuVOKDUMIzlW+WyG8Ym+up0YcyXAz1ktpTeJ5nPeT/FPh4OWR9ACaDlTO3zIi3k0K/KpI6iKcfUSaBYq3f0g8ljuy4Mth/kLjW8mNxdhVmekg/mLpY6nrh34HEhoIJq2s5zUBtBSoSC3Fq7NA1cXgwkgB/hYSAGb8MExCC5OoyTggeKvOmy4BvGJ+B+vynDGhYMrKWbRYO37mmuZenX3UzS0k3N8c6yhJOFVyk3E8z1kuFFa1ehvkAMn+0DVjk9Mrei+eu8WOrX5H6DAfyaL3/hfEdUenB56hiCRB0LFuAFXbo/caCN1M0p5p4RCvg9FZ0gv8BHFnb/1Unn/lSzTnLGzwYxm3/cHsZx5ZE="
  app: jfkatms
  on: master
